name: taktische_zeichen
description: "Taktische Zeichen WebGenerator"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  jinja: ^0.6.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_form_builder: ^9.3.0
  async_builder: ^1.3.1+1
  file_saver: ^0.2.13
  url_launcher: ^6.3.0
  form_builder_extra_fields: ^10.2.0
  package_info_plus: ^8.0.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  rename_app: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Taktische-Zeichen/templates/
    - assets/Taktische-Zeichen/fonts/
    - assets/Taktische-Zeichen/symbols/
    - assets/Taktische-Zeichen/symbols/Bundeswehr_Einheiten/
    - assets/Taktische-Zeichen/symbols/Bundeswehr_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Bundeswehr_Personen/
    - assets/Taktische-Zeichen/symbols/Einheiten/
    - assets/Taktische-Zeichen/symbols/Einrichtungen/
    - assets/Taktische-Zeichen/symbols/Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Fernmeldewesen/
    - assets/Taktische-Zeichen/symbols/Feuerwehr_Einheiten/
    - assets/Taktische-Zeichen/symbols/Feuerwehr_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Feuerwehr_Gebäude/
    - assets/Taktische-Zeichen/symbols/Feuerwehr_Personen/
    - assets/Taktische-Zeichen/symbols/Führungsstellen/
    - assets/Taktische-Zeichen/symbols/Gebäude/
    - assets/Taktische-Zeichen/symbols/Gefahren/
    - assets/Taktische-Zeichen/symbols/Katastrophenschutz_Einheiten/
    - assets/Taktische-Zeichen/symbols/Kommunal_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Maßnahmen/
    - assets/Taktische-Zeichen/symbols/Personen/
    - assets/Taktische-Zeichen/symbols/Polizei_Einheiten/
    - assets/Taktische-Zeichen/symbols/Polizei_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Rettungswesen_Einheiten/
    - assets/Taktische-Zeichen/symbols/Rettungswesen_Einrichtungen/
    - assets/Taktische-Zeichen/symbols/Rettungswesen_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/Rettungswesen_Personen/
    - assets/Taktische-Zeichen/symbols/Schäden/
    - assets/Taktische-Zeichen/symbols/Schadenskonten/
    - assets/Taktische-Zeichen/symbols/Schadenskonten/gelb/
    - assets/Taktische-Zeichen/symbols/Schadenskonten/rot/
    - assets/Taktische-Zeichen/symbols/Schadenskonten/weiß/
    - assets/Taktische-Zeichen/symbols/Sonstiges/
    - assets/Taktische-Zeichen/symbols/THW_Einheiten/
    - assets/Taktische-Zeichen/symbols/THW_Einheiten/ÖGA/
    - assets/Taktische-Zeichen/symbols/THW_Einheiten/SysBR500/
    - assets/Taktische-Zeichen/symbols/THW_Einrichtungen/
    - assets/Taktische-Zeichen/symbols/THW_Fahrzeuge/
    - assets/Taktische-Zeichen/symbols/THW_Führungsstellen/
    - assets/Taktische-Zeichen/symbols/THW_Gebäude/
    - assets/Taktische-Zeichen/symbols/THW_Personen/
    - assets/Taktische-Zeichen/symbols/Wasserrettung_Einheiten/
    - assets/Taktische-Zeichen/symbols/Zoll_Einheiten/
    - assets/Taktische-Zeichen/symbols/Zoll_Fahrzeuge/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
