name: Auto Tagging

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        type: boolean
        description: 'Tag the current commit with the version number'
        required: false
        default: false
  push:
    branches: [ master ]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.44.2
        id: get_version
        with:
          cmd: yq '.version' pubspec.yaml
      - uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.get_version.outputs.result }}';
            const [major, minor, patch] = version.split('.').map(Number);
            const commit = context.sha.substring(0, 7);

            const reset = '\u001b[33;0m';
            const cyan = '\u001b[33;36m';
            core.info(`Version: ${cyan}${version}${reset}`);
            core.info(`Commit: ${cyan}${commit}${reset}`);
            core.info('-'.repeat(80));

            if (context.eventName === 'workflow_dispatch' && context.payload.inputs.tag === 'true') {
              for (const tag of [
                `${major}.${minor}.${patch}`,
                `${major}.${minor}`
              ]) {
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${tag}`,
                  sha: context.sha
                });
                core.info(`Updated version tag: ${cyan}${tag}${reset}`);
              }
            } else {
              const tag = `${major}.${minor}.${patch}-dev`;
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`,
                sha: context.sha
              });
              core.info(`Updated dev-version tag: ${cyan}${tag}${reset}`);
            }
