name: Auto Tagging

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.44.2
        id: get_version
        with:
          cmd: yq '.version' pubspec.yaml
      - run: echo ${{ steps.get_version.outputs.result }}
