name: Auto Tagging

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.44.2
        id: get_version
        with:
          cmd: yq '.version' pubspec.yaml
      - uses: actions/github-script@v7
        id: create_tag
        with:
          script: |
            const version = '${{ steps.get_version.outputs.result }}';
            const build_number = context.sha.substring(0, 7);
            const tag = `${version}+${build_number}`;

            const reset = '\u001b[33;0m';
            const cyan = '\u001b[33;36m';
            core.info(`Version: ${cyan}${version}${reset}`);
            core.info(`Build: ${cyan}${build_number}${reset}`);

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            });

            core.setOutput('tag', tag);
      - uses: fischerscode/tagger@v0.2
        with:
          tag: ${{ steps.create_tag.outputs.tag }}
